# -*- coding: utf-8 -*-
"""CNN_THUATBUI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c9k1ihwCkP551g-ApUDC2S7X7NLpMtIs
"""

from keras.models import Sequential
from keras.layers import Conv2D, MaxPool2D, Dense, Flatten, Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import cv2
import numpy as np
import matplotlib.pyplot as plt


train_dir = '/content/drive/MyDrive/Ảnh Lớp IC'

img_width, img_height = 280, 280
batch_size = 32

train_datagen = ImageDataGenerator(
    rescale=1/255,
    shear_range=0.2,
    zoom_range=0.2,
    height_shift_range=0.2,
    width_shift_range=0.2, # Sửa tên biến từ img_width_shift_range thành width_shift_range
    horizontal_flip=True,
    fill_mode='nearest'
)

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode='categorical'
)

from keras.layers import Input, Conv2D, MaxPool2D, MaxPooling2D, Dense, Flatten, Dropout

model = Sequential([
    Input(shape=(img_width, img_height, 3)),
    Conv2D(33, (3, 3), activation='relu'),
    MaxPool2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(34, activation='softmax')
])

model.compile(optimizer="rmsprop", loss="categorical_crossentropy", metrics=["accuracy"])
model.summary()
epochs=30
history=model.fit(train_generator, epochs=epochs)

from keras.utils import load_img
import numpy as np
path="/content/drive/MyDrive/Ảnh Lớp IC/Minh Tiến/z7860433607370_3ade5a9c051de54b33b4a26070fd62a6.jpg"
img=load_img(path,target_size=(280,280))
plt.imshow(img)
img=np.array(img)
img=img/255.0
img=img.reshape(1,280,280,3)
prediction=np.argmax(model.predict(img))
class_labels={v:k for k, v in train_generator.class_indices.items()}
person_name=class_labels[prediction]
print(f"Người tiên đoán:{person_name}")